import "@/styles/index.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// 375*812 (ios) 크기.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
