name: AI Code Review

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    review:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requests

            - name: Run AI Code Review
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
                python .github/scripts/ai_code_review.py